I'm using this tutorial to extract a map and plot the data: https://towardsdatascience.com/easy-steps-to-plot-geographic-data-on-a-map-python-11217859a2db

https://ramiro.org/notebook/basemap-choropleth/

In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/marine-litter-watch-19502021/MLW_Data.csv
/kaggle/input/marine-litter-watch-19502021/MLW_Meta.csv

In [12]:
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('../input/marine-litter-watch-19502021/MLW_Data.csv', delimiter=',', encoding = "ISO-8859-1")

In [20]:
df.head()

,CommunityName,BeachName,BeachCountrycode,BeachRegionalSea,BeachLength_m,BeachLocation,BeachType,EventDate,EventType,NatRef,...,G202,G203,G204,G205,G206,G207,G208,G210,G211,G213
0,gBqsPxAZ,krapetz,BG,Black Sea,5850,Rural,Sandy,20160310,Cleanup,NaN,...,2.0,4.0,NaN,3.0,NaN,NaN,3.0,NaN,1.0,NaN
1,gBqsPxAZ,krapetz,BG,Black Sea,5850,Rural,Sandy,20150902,Cleanup,NaN,...,1.0,NaN,2.0,NaN,NaN,NaN,7.0,3.0,NaN,NaN
2,gBqsPxAZ,krapetz,BG,Black Sea,5850,Rural,Sandy,20151203,Cleanup,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,2.0,NaN,2.0,1.0
3,gBqsPxAZ,krapetz,BG,Black Sea,5850,Rural,Sandy,20151008,Cleanup,NaN,...,5.0,NaN,2.0,NaN,NaN,NaN,5.0,26.0,NaN,NaN
4,Legambiente Onlus,San Mauro Cilento (SA),IT,Unknown,100,NaN,NaN,20180428,Monitoring,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN

In [22]:
len(df.columns)

176

In [24]:
for each in df.columns:
    print(each)

CommunityName
BeachName
BeachCountrycode
BeachRegionalSea
BeachLength_m
BeachLocation
BeachType
EventDate
EventType
NatRef
lon_x1
lat_y1
lon_x2
lat_y2
G1
G3
G4
G5
G7
G8
G9
G10
G11
G12
G13
G14
G15
G16
G17
G18
G19
G21
G22
G23
G24
G25
G26
G27
G28
G29
G30
G31
G32
G33
G34
G35
G36
G37
G40
G41
G42
G43
G44
G45
G46
G47
G49
G50
G52
G53
G54
G56
G57
G58
G59
G60
G62
G63
G64
G65
G66
G67
G68
G69
G70
G71
G72
G73
G76
G77
G79
G80
G82
G83
G84
G85
G86
G87
G88
G89
G90
G91
G92
G93
G95
G96
G97
G98
G99
G100
G101
G102
G124
G125
G126
G127
G128
G129
G130
G131
G132
G133
G134
G137
G138
G139
G140
G141
G142
G143
G144
G145
G147
G148
G150
G151
G152
G153
G154
G155
G156
G158
G159
G160
G161
G162
G163
G164
G165
G166
G167
G171
G172
G174
G175
G176
G177
G178
G179
G180
G181
G182
G184
G186
G187
G188
G189
G190
G191
G193
G194
G195
G198
G199
G200
G201
G202
G203
G204
G205
G206
G207
G208
G210
G211
G213

In [26]:
df_coords = df[["lon_x1", "lat_y1", "lon_x2", "lat_y2"]]
df_coords

         lon_x1     lat_y1     lon_x2     lat_y2
0     28.564998  43.695538  28.574143  43.643309
1     28.564998  43.695538  28.574143  43.643309
2     28.564998  43.695538  28.574143  43.643309
3     28.564998  43.695538  28.574143  43.643309
4      0.000135   0.000361   0.000135   0.000361
...         ...        ...        ...        ...
3408  13.302130  43.671250  13.303130  43.671250
3409  -1.249080  44.548088  -1.250983  44.543342
3410  -1.875802  50.715493  -1.843531  50.719876
3411   9.291067  47.614022   9.291365  47.614005
3412  -2.236120  36.770780  -2.235120  36.770780

[3413 rows x 4 columns]

In [32]:
BBox = ((df_coords.lon_x1.min(),df_coords.lon_x1.max(), df_coords.lat_y1.min(), df_coords.lat_y1.max()))
BBox

(-149.5509999997767,
 166.44199999987387,
 -36.538300000212246,
 73.66193622913302)

In [40]:
df_country = df.groupby('BeachCountrycode').count()
df_country = df_country['name']

In [42]:
df_country

,CommunityName,BeachName,BeachRegionalSea,BeachLength_m,BeachLocation,BeachType,EventDate,EventType,NatRef,lon_x1,...,G202,G203,G204,G205,G206,G207,G208,G210,G211,G213
BeachCountrycode,,,,,,,,,,,,,,,,,,,,,
BA,2,2,1,2,2,2,2,2,0,2,...,1,0,0,0,0,0,2,0,0,0
BE,4,4,4,4,3,3,4,4,0,4,...,0,0,0,0,0,0,3,0,0,0
BG,74,74,74,74,68,68,74,74,0,74,...,22,3,22,9,0,0,36,13,13,1
CH,985,985,1,985,514,514,985,985,0,985,...,0,569,628,0,0,0,768,571,596,573
CV,4,4,4,4,4,4,4,4,0,4,...,3,0,0,0,0,0,0,3,0,0
CY,8,8,8,8,8,8,8,8,0,8,...,0,1,3,0,1,1,4,3,2,1
DE,89,89,5,89,48,48,89,89,0,89,...,0,35,41,0,0,0,64,35,41,38
DK,256,256,256,256,204,213,256,256,1,256,...,22,21,94,2,0,0,126,29,38,60
DZ,2,2,2,2,0,0,2,2,0,2,...,0,0,0,0,0,0,2,0,0,0
EE,2,2,2,2,1,1,2,2,1,2,...,0,0,0,0,0,1,1,1,0,1
EL,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
ES,366,366,366,366,267,275,366,366,0,366,...,12,0,83,0,0,0,121,106,40,57
FI,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
FR,316,316,311,316,40,40,316,316,0,316,...,2,0,6,0,0,0,229,4,13,99
GE,20,20,20,20,20,20,20,20,5,20,...,10,0,2,1,0,0,10,4,4,0
GR,67,67,67,67,54,54,67,67,5,67,...,5,1,8,1,0,0,45,3,5,0
HR,7,7,7,7,5,7,7,7,2,7,...,0,0,1,0,0,0,3,0,3,0
IE,42,42,42,42,9,9,42,42,0,42,...,0,0,0,0,0,0,33,2,2,0
IL,3,3,3,3,3,3,3,3,0,3,...,0,0,0,0,0,0,1,0,0,0
IT,511,511,511,511,28,28,511,511,2,511,...,68,148,216,36,120,116,219,166,112,12
Int,23,23,3,23,0,0,23,23,0,23,...,0,0,0,0,0,0,17,0,0,0
LB,1,1,1,1,0,0,1,1,0,1,...,0,0,0,0,0,0,0,0,0,1
MA,3,3,1,3,0,0,3,3,0,3,...,0,0,0,0,0,0,3,0,0,1
ME,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
MT,2,2,2,2,2,2,2,2,0,2,...,0,0,0,0,0,0,1,0,0,0
NL,10,10,10,10,6,6,10,10,0,10,...,0,0,0,0,0,0,6,0,0,0
NO,2,2,2,2,1,1,2,2,0,2,...,0,1,0,0,0,0,1,0,0,0
PT,25,25,25,25,15,15,25,25,0,25,...,1,0,4,0,0,0,14,2,1,4
RO,145,145,145,145,144,145,145,145,93,145,...,8,10,76,1,1,0,82,24,44,11
RU,21,21,21,21,20,20,21,21,0,21,...,1,4,8,0,0,0,5,2,9,1
SE,5,5,5,5,3,3,5,5,0,5,...,0,0,0,0,1,0,3,0,0,1
SI,77,77,77,77,76,77,77,77,1,77,...,0,2,27,0,0,0,71,5,15,2
TN,4,4,4,4,3,3,4,4,0,4,...,0,0,1,0,0,0,3,0,1,1
TR,20,20,20,20,20,20,20,20,3,20,...,3,2,3,1,0,0,6,1,2,1
UA,6,6,6,6,6,6,6,6,0,6,...,2,0,5,0,0,0,3,2,1,0
UK,55,55,55,55,36,37,55,55,1,55,...,0,0,0,0,0,0,30,2,2,2
ZA,4,4,0,4,4,4,4,4,0,4,...,0,0,0,0,0,0,2,0,0,0

In [48]:
count = df['BeachCountrycode'].value_counts() 
country_count = count.to_frame()
country_count

     BeachCountrycode
CH                985
IT                511
ES                366
FR                316
DK                256
RO                145
DE                 89
SI                 77
BG                 74
GR                 67
UK                 55
IE                 42
PT                 25
Int                23
RU                 21
GE                 20
TR                 20
NL                 10
CY                  8
HR                  7
UA                  6
SE                  5
TN                  4
BE                  4
ZA                  4
CV                  4
MA                  3
IL                  3
NO                  2
MT                  2
BA                  2
DZ                  2
EE                  2
EL                  1
FI                  1
ME                  1
LB                  1

In [61]:
# country = [CH, IT, ES, FR. DK, RO, DE, SI, BG, GR, UK, IE, PT, RU, GE, TR, NL, CY, HR, UA, SE, TN, BE, ZA, CV, MA, IL, NO, MT, BA, DZ, EE, EL, FI, ME, LB]
country = ["CHE", "ITA", "ESP", "FRA", "DNK", "ROU", "DEU", "SVN", "BGR", "GRC", "GBR", "IRL", "PRT", "RUS", "GEO", "TUR", "NLD", "CYP", "HRV", "UKR", "SWE", "TUN", "BEL", "ZAF", "CPV", "MAR", "ISR", "NOR", "MLT", "BIH", "DZA", "EST", "FIN", "MNE", "LBN"]
count = [985, 511, 366, 316, 256, 145, 89, 77, 74, 67, 55, 42, 25, 21, 20, 20, 10, 8, 7, 6, 5, 4, 4, 4, 4, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1]

print(len(country), len(count))
d = {'country': country, 'count': count}
map_data = pd.DataFrame(data=d)

35 35

In [64]:
import plotly.express as px

df = map_data
fig = px.choropleth(df, locations="country",
                    color="count", 
                    hover_name="country", # column to add to hover information
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.show()

Next, I want to explort the plotly as HTML https://medium.com/analytics-vidhya/how-to-export-a-plotly-chart-as-html-3b5df568df4a